### ISSUE TITLE
How to upgrade to quartz 4? (make update doesn't work)

### ISSUE THREAD

**Issue by houstonhaynes** [64bitpandas/amethyst#3]
**Is your feature request related to a problem? Please describe.**
I would like to be able to upgrade to quartz v4 as there's a bug in styling that's fixed in the latest version

**Describe the solution you'd like**
Understand how to upgrade the version of quartz in this project/theme. It's not entirely clear since the only two folders I see under "assets/quartz" are "js" and "styles"

**Describe alternatives you've considered**
None

**Additional context**
I'm just looking for a way to get my head wrapped around *how* Quartz is used here. If there was a way that I could do the upgrade and post a PR, I'd do the honors. But the mismatch between what I see in the structure here and the full quartz repo gives me pause.

**Comment by houstonhaynes** [comment]
Update - I just saw the notes in the Makefile to the effect that 'make update' should work, but it doesn't.

**Comment by 64bitpandas** [comment]
It appears that Quartz v4 was re-written for (p)react, so unfortunately I don't think an upgrade to Amethyst will be possible without a full rewrite of some sort, given that it's currently a Hugo theme.

If you want to investigate further though, most of the original code was split between `assets/quartz` and `layouts/partials/quartz`.

**Comment by houstonhaynes** [comment]
Thanks - I'll take a look. 👍
